name: Run GameTest

on: [ push ]

jobs:
  gametest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
          server-id: github
          settings-path: ${{ github.workspace }}

      # Requires a gametest run config to be defined in build.gradle
      - name: Run GameTests
        run: gradle runGametest

      - name: Publish GameTest Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()  # Otherwise it will not invoke when testing fails
        with:
          files: run/test_results.xml

      - name: Upload Test World
        uses: actions/upload-artifact@v2
        if: always()  # Otherwise it will not invoke when testing fails
        with:
          name: test-world
          path: run/test_world.zip
